### ISSUE TITLE
Sync not idempotent w.r.t. queues

### ISSUE THREAD

**Issue by TimoMaarse** [jwbuurlage/Bulk#12]
Seeing the source comment on `World::sync`, it is clear that it is intended behaviour for `World::sync` to clear message queues, but this was unexpected for me. I searched the web documentation but couldn't find that behaviour made explicit (but I admin I didn't reread all documentation).

As the documentation for `queue` describes it as an inbox, maybe it makes more sense to consume messages by iterating over them? (Unfortunately, I don't know whether side effects for iterators as implemented in C++ are idiomatic...)

For context: I now have two supersteps sending messages intended for the third superstep, so without commenting out the queue clearing in `World::sync` and exposing the queue implementation's clear method, I would have to manually buffer the messages in the second superstep.

**Comment by jwbuurlage** [comment]
Thanks for bringing this up.

This is the intended behavior, and as far as I know is also consistent with the behavior of BSPlib. However, after browsing through the docs myself it is clear that this is not explained in the introduction, or the API documentation. I will add a note to 1) introduction, 2) API docs at `world::sync`, as well as `queue`.

I don't think iterating over the queue should consume the messages, as there are many use cases where you would want to iterate over a queue multiple times (without copying the messages into a buffer).

For your use case, you will indeed have to buffer the contents of the queue at the receiving processor in the second superstep for now. A solution would be to add a `clear_queues=true` optional argument to `world::sync` but this feels very ad-hoc to me. What do you think?

**Comment by jwbuurlage** [comment]
I implemented the optional flag to `world::sync` in https://github.com/jwbuurlage/Bulk/commit/17e9e8ea7e8ddf43a735b2d73a9586d03a0cc1db, let me know what you think and if that solves your use case.

**Comment by TimoMaarse** [comment]
> This is the intended behavior, and as far as I know is also consistent with the behavior of BSPlib. However, after browsing through the docs myself it is clear that this is not explained in the introduction, or the API documentation. I will add a note to 1) introduction, 2) API docs at world::sync, as well as queue.

Nice!

> I implemented the optional flag to world::sync in 17e9e8e, let me know what you think and if that solves your use case.

That solves my use case perfectly! :smile: However, I agree it is a bit ad hoc (but not necessarily bad). Another way I see is giving queues a `persistent` flag, that way you also have more control over which queues are cleared and when (in combination with making the `clear` method public). However, if this is not a common need adding a flag to every queue for this specific purpose doesn't seem like a great idea...

**Comment by jwbuurlage** [comment]
Yeah, that would be a more flexible solution, but also might add some boilerplate when wanting this behavior for multiple queues. Making the clear method public would probably be a good idea regardless of this flag, so I've done that in https://github.com/jwbuurlage/Bulk/commit/25ae9b1b9b378cfa08e585e828b3e29e85b74723.

I'll think about the persistent queues some more. Let me know if you run into anything else!

**Comment by TimoMaarse** [comment]
Thank you for the quick response, and will do!
