### ISSUE TITLE
.gitignore malformed?

### ISSUE THREAD

**Issue by ahendriksen** [jwbuurlage/Bulk#7]
Hi, 

Thank you for making this great software package! While I was searching through my directories, [ripgrep](https://github.com/BurntSushi/ripgrep) complained that the .gitignore file is malformed: 

```
line 1: error parsing glob '**.swp': invalid use of **; must be one path component
```
Should it not be `*.swp`?

**Comment by jwbuurlage** [comment]
Thanks!
