### ISSUE TITLE
partition swapped? 

### ISSUE THREAD

**Issue by Lukas3226** [jwbuurlage/Bulk#8]
https://github.com/jwbuurlage/Bulk/blob/31fec4c80271d4cf600483e428a4c780fb129a37/examples/psc/psc_example.cpp#L41

I think you intend to use the block_partition initialized in line 40, if I'm not mistaken. 
`auto x = psc::vector<int>(world, block); `

**Comment by jwbuurlage** [comment]
Thanks! Fixed in 16962c9 :)

In principle, the partitioning that is used does not matter for a random vector like this (since the result is a coarray with various local sizes). I do think this makes more sense intuitively though, which is why I intended to use the block partitioning.
